name: Weekly Tag Creation

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

jobs:
  create-new-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine the latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git ls-remote -q --tags --sort=committerdate | grep -o 'v.*' | sort -Vr | head -1)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Increment the tag
        id: increment-tag
        run: |
          latest_tag=${{ env.latest_tag }}
          major=$(echo $latest_tag | cut -d. -f1 | cut -c2-)
          minor=$(echo $latest_tag | cut -d. -f2)
          patch=$(echo $latest_tag | cut -d. -f3)
          new_patch=$((patch + 1))
          new_tag="v$major.$minor.$new_patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Push the new tag
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
          gh workflow run docker-build-and-push.yml --ref ${{ env.new_tag }}
