name: Weekly Tag Creation

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow
  
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create-new-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push tags to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine the latest tag
        id: get-latest-tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Increment the tag
        id: increment-tag
        run: |
          latest_tag=${{ env.latest_tag }}
          major=$(echo $latest_tag | cut -d. -f1 | cut -c2-)
          minor=$(echo $latest_tag | cut -d. -f2)
          patch=$(echo $latest_tag | cut -d. -f3)
          new_patch=$((patch + 2))
          new_tag="v$major.$minor.$new_patch"
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Push the new tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ env.new_tag }}
          git push origin ${{ env.new_tag }}
          gh workflow run docker-publish.yml --ref ${{ env.new_tag }}